---
test:
  clients:
    type: local
    number: 5
  rounds:
  - label: init
    txNumber:
    - 25
    - 50
    - 75
    rateControl:
    - type: fixed-rate
      opts:
        tps: 5
    - type: fixed-rate
      opts:
        tps: 50
    - type: fixed-rate
      opts:
        tps: 75
    callback: benchmark/supply/init.js
  - label: query
    txNumber:
    - 15
    rateControl:
    - type: fixed-rate
      opts:
        tps: 5
    - type: fixed-rate
      opts:
        tps: 10
    callback: benchmark/supply/query.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1